### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by CalQL8ed-K-OS**
First, I can't make a branch for you, so this PR should really have a base of some branch you'd create.

It's interesting that this becomes a category on the new `Date` struct instead of the old `NSDate` class.
That said it doesn't seem to have changed any behavior that I can see.
Let me know if I can do anything to help.

### CODE REVIEW

**Comment by mikaelbo** [comment]
It would be great to have an update for Beta4 ^_^

**Comment by CalQL8ed-K-OS** [comment]
I'll try to get to that soon

**Comment by CalQL8ed-K-OS** [comment]
I've updated for beta 4 @mikaelbo 
Had to figure out what the correct new APIs were, and I think I got them all right :D

**Comment by mikaelbo** [comment]
@CalQL8ed-K-OS Awesome! I just forked the project and tried to do it myself, but I'm sure there's something I've missed ^_^. I'm not the most experienced with tests, but I thinking about adding some to ensure further "code migrations" feel safer and easier to do :)

**Comment by CalQL8ed-K-OS** [comment]
That would be sweet, let me know if you feel you need some help, I'd be happy to assist.

**Comment by mikaelbo** [comment]
@CalQL8ed-K-OS Okay, will do! :)

**Comment by CalQL8ed-K-OS** [comment]
You should probably update the readme since this is Swift 3 now

**Comment by melvitax** [comment]
l'll update right after I fix some of the errors we now have

**Comment by melvitax** [comment]
Fixed errors, updated version, read me and pod spec.  Thanks @CalQL8ed-K-OS and @mikaelbo  for porting it. I tried cocoa pods but encountered "Encountered an unknown error (Simulator iPhone 4s is not available.) during validation" which I'm not clear on.

**Pull request merged**
